image: Visual Studio 2017

platform:
  - x64

cache:
  - node_modules
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 9 x64
  - git config --file=.gitmodules submodule.bitfocus-skeleton.url https://github.com/bitfocus/bitfocus-skeleton.git
  - git config --file=.gitmodules submodule.bitfocus-libs.url https://github.com/bitfocus/bitfocus-libs.git
  - cmd: bash tools/yarn.sh
  - cmd: bash tools/build_writefile.sh
  - yarn

environment:
  TRAVIS_OS_NAME: win64

artifacts:
  - path: electron-output/*.exe
    name: Installer

build_script:
  - yarn windist
  - cmd: bash tools/build_rename_git.sh

test: off

deploy:
  - provider: FTP
    host: w014ec4c.kasserver.com
    protocol: ftp
    username: f01095fe
    password:
      secure: 91N9eXfCgvQhTqpDwEN0hw==
